# SPDX-License-Identifier: MIT

"""Guard the docs lists that are generated from code against drift.

Why this guard exists. Hand-written lists of CLI commands, slash commands and
conformity validators drifted from the code: the architecture page listed 12 of
13 CLI commands, 14 of 45 shipped slash commands had no page, the command nav
omitted ``/plan-amend``, and the conformity-gate page documented a ``--sweep``
flag that does not exist and 15 of 52 validators. The lists are now generated by
``site/scripts/update-reference-inventory.mjs`` from the same sources the code
uses. These tests assert the committed pages match those sources, so a new
command, validator or CLI verb that lands without a regenerated page fails here
as well as in the docs-drift workflow.

The tests read the source of truth directly (the Click tree via
``apothem.cli.reference_export``, the command definitions under
``src/apothem/commands/``, and the conformity modules), never a copy of it.
"""

from __future__ import annotations

import json
import pathlib
import re
import shlex

import pytest

from apothem.cli import reference_export
from apothem.conformity import gate

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
_DOCS_ROOT = _REPO_ROOT / "site" / "content" / "docs"
_COMMANDS_ROOT = _REPO_ROOT / "src" / "apothem" / "commands"

_START = "{/* apothem:generated-reference:start */}"
_END = "{/* apothem:generated-reference:end */}"

# The gate's command-line surface. ``--help`` is listed because the docs
# describe it; the gate's own parser owns its behaviour.
_GATE_FLAGS = frozenset(
    {"--all", "--all-perwrite", "--strict", "--check", "--list", "--hook", "--help"}
)
_GATE_INVOCATION = re.compile(
    r"python3? -m apothem\.conformity\.gate\b(?P<args>[^\n]*)"
)
_FENCE = re.compile(r"^[ \t]*```")
_LOCALES = frozenset(
    {"ar", "de", "es", "fr", "hi", "id", "ja", "ko", "pt-br", "ru", "zh-cn"}
)


def _generated_region(text: str) -> str:
    """Return the text between the generated-reference markers.

    Fails the calling test when the page has no well-formed marker pair, since
    a page without markers cannot be regenerated.
    """
    start = text.find(_START)
    end = text.find(_END)
    assert start != -1, "generated-reference start marker missing"
    assert end > start, "generated-reference end marker missing or misplaced"
    return text[start + len(_START) : end]


def _shipped_command_names() -> list[str]:
    """Return every shipped slash-command name (one per definition file)."""
    return sorted(
        path.stem for path in _COMMANDS_ROOT.glob("*.md") if path.name != "README.md"
    )


def _english_pages() -> list[pathlib.Path]:
    """Return every English docs page (locale subtrees excluded)."""
    pages = []
    for path in sorted(_DOCS_ROOT.rglob("*.mdx")):
        rel = path.relative_to(_DOCS_ROOT)
        if rel.parts[0] in _LOCALES:
            continue
        pages.append(path)
    return pages


def test_source_layout_lists_every_top_level_cli_command() -> None:
    """The architecture page names every top-level CLI command, from the Click tree."""
    commands = reference_export.export_cli()["commands"]
    assert isinstance(commands, list)
    top_level = sorted({str(entry["name"]).split()[0] for entry in commands})
    assert "migrate-workspace" in top_level  # anti-vacuous anchor

    page = (_DOCS_ROOT / "architecture" / "source-layout.mdx").read_text(
        encoding="utf-8"
    )
    listed = re.findall(r"`apothem ([a-z][a-z-]*)`", _generated_region(page))
    assert listed == top_level


def test_every_shipped_command_has_an_english_page() -> None:
    """Each ``src/apothem/commands/<name>.md`` has ``pipeline/<name>.mdx``."""
    names = _shipped_command_names()
    # Anti-vacuous anchor: the shipped set at the time of writing.
    assert len(names) >= 45
    missing = [
        name
        for name in names
        if not (_DOCS_ROOT / "pipeline" / f"{name}.mdx").is_file()
    ]
    assert missing == [], f"commands without a docs page: {missing}"


def test_pipeline_nav_lists_every_command_exactly_once() -> None:
    """The command sidebar names each shipped command once, in English and every locale."""
    names = set(_shipped_command_names())
    metas = [_DOCS_ROOT / "pipeline" / "meta.json"]
    metas += sorted(_DOCS_ROOT.glob("*/pipeline/meta.json"))
    assert len(metas) == 1 + len(_LOCALES)
    for meta in metas:
        pages = json.loads(meta.read_text(encoding="utf-8"))["pages"]
        listed = [page for page in pages if page in names]
        assert sorted(listed) == sorted(names), (
            f"{meta.relative_to(_DOCS_ROOT)} nav drift"
        )
        assert len(listed) == len(set(listed)), (
            f"{meta.relative_to(_DOCS_ROOT)} lists a page twice"
        )


def test_pipeline_overview_diagram_shows_every_plan_stage() -> None:
    """The /plan flow diagram includes every ``plan-*`` command, ``/plan-amend`` included."""
    page = (_DOCS_ROOT / "pipeline" / "index.mdx").read_text(encoding="utf-8")
    diagram = page.split("```mermaid", 1)[1].split("```", 1)[0]
    stages = [name for name in _shipped_command_names() if name.startswith("plan-")]
    assert "plan-amend" in stages
    missing = [name for name in stages if f"/{name}" not in diagram]
    assert missing == [], f"plan stages absent from the overview diagram: {missing}"


def test_conformity_export_covers_every_validator_module() -> None:
    """The conformity export lists every module that declares a ``GREP_NAME``."""
    payload = reference_export.export_conformity()
    assert payload["kind"] == "conformity"
    validators = payload["validators"]
    assert isinstance(validators, list)
    names = [str(entry["name"]) for entry in validators]
    assert names == sorted(names)
    listed = json.loads(gate._list_validators())
    # Every listed validator, plus the change-set ones the gate does not list.
    assert len(names) >= int(listed["total"])
    modes = {str(entry["name"]): str(entry["mode"]) for entry in validators}
    assert modes["hedging-grep"] == "per-write"
    assert modes["naming-grep"] == "standalone"
    assert modes["semver-stability-grep"] == "change-set"
    for entry in validators:
        assert entry["summary"], f"{entry['name']} has no summary line"


def test_conformity_gate_page_documents_every_validator() -> None:
    """The gate page's validator table is the generated export, row for row."""
    page = (_DOCS_ROOT / "conformity-gate" / "index.mdx").read_text(encoding="utf-8")
    rows = re.findall(
        r"^\| `([a-z0-9-]+)` \|", _generated_region(page), flags=re.MULTILINE
    )
    validators = reference_export.export_conformity()["validators"]
    assert isinstance(validators, list)
    assert rows == [str(entry["name"]) for entry in validators]


def _gate_invocations() -> list[tuple[str, list[str]]]:
    """Return ``(page, argv)`` for every gate command inside an English code fence."""
    found = []
    for path in _english_pages():
        in_fence = False
        for line in path.read_text(encoding="utf-8").splitlines():
            if _FENCE.match(line):
                in_fence = not in_fence
                continue
            if not in_fence:
                continue
            match = _GATE_INVOCATION.search(line)
            if match:
                args = match.group("args").split("#", 1)[0].rstrip(" \\")
                found.append((str(path.relative_to(_DOCS_ROOT)), shlex.split(args)))
    return found


def test_docs_gate_invocations_use_real_flags_and_validator_names() -> None:
    """Every documented gate command line uses a real flag and a resolvable ``--check`` name."""
    invocations = _gate_invocations()
    # Anti-vacuous anchor: the harness pages each show one.
    assert len(invocations) >= 10
    problems = []
    for page, argv in invocations:
        for index, arg in enumerate(argv):
            if arg.startswith("--") and arg not in _GATE_FLAGS:
                problems.append(f"{page}: unknown flag {arg}")
            if arg == "--check":
                if index + 1 >= len(argv):
                    problems.append(f"{page}: --check without a validator name")
                    continue
                name = argv[index + 1]
                if name.startswith("<"):
                    continue  # a placeholder such as <name>
                try:
                    gate._resolve_validator(name)
                except ValueError:
                    problems.append(f"{page}: unknown validator {name}")
    assert problems == []


@pytest.mark.parametrize("page", ["conformity-gate/index.mdx"])
def test_gate_page_is_titled_for_its_subject(page: str) -> None:
    """The gate page title names the page, so the browser tab is not "Index"."""
    text = (_DOCS_ROOT / page).read_text(encoding="utf-8")
    title = re.search(r'^title: "(?P<title>[^"]+)"', text, flags=re.MULTILINE)
    assert title is not None
    assert title.group("title") != "Index"


def _harness_entries() -> dict[str, dict[str, object]]:
    """Return the harness export keyed by public adapter id."""
    harnesses = reference_export.export_harnesses()["harnesses"]
    assert isinstance(harnesses, list)
    return {str(entry["id"]): entry for entry in harnesses}


def test_harness_export_carries_the_capability_cells() -> None:
    """The harness export carries each adapter's capability status and notes."""
    entries = _harness_entries()
    claude = entries["claude-code"]
    capabilities = claude["capabilities"]
    notes = claude["capability_notes"]
    assert isinstance(capabilities, dict)
    assert isinstance(notes, dict)
    assert capabilities["mcp_servers"] != "native"
    assert notes["mcp_servers"]
    opencode_capabilities = entries["opencode"]["capabilities"]
    assert isinstance(opencode_capabilities, dict)
    assert opencode_capabilities["mcp_servers"] == "native"


def test_mcp_page_names_each_adapter_projection_from_the_registry() -> None:
    """The MCP page's adapter table is generated from the registry's MCP cells."""
    page = (_DOCS_ROOT / "reference" / "mcp.mdx").read_text(encoding="utf-8")
    region = _generated_region(page)
    for harness_id, entry in _harness_entries().items():
        capabilities = entry["capabilities"]
        assert isinstance(capabilities, dict)
        expected = (
            "Projected" if capabilities["mcp_servers"] == "native" else "Not projected"
        )
        row = re.search(
            rf"^\| [^|]*\(`{re.escape(harness_id)}`\) \| (?P<cell>[^|]+) \|",
            region,
            flags=re.MULTILINE,
        )
        assert row is not None, f"{harness_id} missing from the MCP table"
        assert row.group("cell").strip().startswith(expected), harness_id
