#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

# Cosign keyless-OIDC sign-blob recipe for the GitHub Releases asset matrix.
#
# Signs every file in dist/release-assets/ via Sigstore cosign in keyless mode
# (Fulcio-issued short-lived certificate; Rekor transparency-log entry). Each
# asset gets one Sigstore bundle,
#   <asset>.cosign.bundle   signature, Fulcio certificate and Rekor entry
# matching what .github/workflows/release.yml publishes, plus
# SHA256SUMS.cosign.bundle signing the manifest itself.
#
# Verification is performed by verify-provenance.sh. SLSA-3 build provenance
# is generated by the release workflow and verified via
# `slsa-verifier verify-artifact`.

set -euo pipefail
IFS=$'\n\t'

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly ASSETS_DIR="${REPO_ROOT}/dist/release-assets"

if ! command -v cosign >/dev/null 2>&1; then
    printf 'sign-assets: cosign not installed; see https://docs.sigstore.dev/cosign/installation/\n' >&2
    exit 1
fi
if [[ ! -d "${ASSETS_DIR}" ]]; then
    printf 'sign-assets: %s not found; run build-release-assets.sh first\n' "${ASSETS_DIR}" >&2
    exit 1
fi

cd "${ASSETS_DIR}"

# Keyless signing requires COSIGN_EXPERIMENTAL=1 on older cosign; current
# releases honor --yes for non-interactive ambient-OIDC flows.
export COSIGN_EXPERIMENTAL=1

# `-printf '%P\n'` is GNU-only (absent on BSD/macOS find, a release target
# platform); enumerate portably and strip the leading `./` from each result.
assets=()
while IFS= read -r _asset; do
    assets+=("${_asset#./}")
#
# SHA256SUMS is excluded here because the block below signs it on its own. Each
# keyless `sign-blob` mints a fresh Fulcio certificate and a Rekor
# transparency-log entry, so enumerating the manifest in both places would
# overwrite its outputs and strand one Rekor entry per release.
done < <(find . -maxdepth 1 -type f ! -name '*.cosign.bundle' ! -name '*.sig' ! -name '*.crt' ! -name 'SHA256SUMS')

for asset in "${assets[@]}"; do
    printf 'sign-assets: signing %s\n' "${asset}" >&2
    cosign sign-blob --yes \
        --bundle "${asset}.cosign.bundle" \
        "${asset}"
done

# Sign the manifest itself last; consumers verify SHA256SUMS first, then per-file.
signed=${#assets[@]}
if [[ -f SHA256SUMS ]]; then
    printf 'sign-assets: signing SHA256SUMS\n' >&2
    cosign sign-blob --yes \
        --bundle SHA256SUMS.cosign.bundle \
        SHA256SUMS
    signed=$((signed + 1))
fi

printf 'sign-assets: signed %d artifacts\n' "${signed}" >&2
printf 'sign-assets: OK\n' >&2
