// SPDX-License-Identifier: MIT

/**
 * hreflang alternate-language link construction for the documentation site.
 *
 * Builds the `alternates.languages` map Next.js renders as
 * `<link rel="alternate" hreflang="…" href="…">` tags in each page's `<head>`,
 * plus the `x-default` fallback. The construction honors the i18n-discipline
 * missing-translation rule: a locale's hreflang link is emitted ONLY when that
 * locale has an authored translation of THIS page. A page still awaiting
 * translation in a locale is OMITTED — never pointed at the English fallback —
 * so search engines are told accurately that no translation exists rather than
 * being lied to.
 *
 * English (the source locale) always emits its self-link plus `x-default`,
 * both resolving to the un-prefixed root URL. Each routed non-default locale
 * emits its alternate only on pages where it has an authored translation under
 * `content/docs/<locale>/`. The set is symmetric: an English page and its
 * translated counterparts emit the identical hreflang cluster because it is
 * derived from the same locale-agnostic path.
 */

import {
  SITE_URL,
  DEFAULT_LOCALE,
  COHORT_LOCALES,
  ROUTED_NON_DEFAULT_LOCALES,
  type CohortLocale,
} from '@/lib/i18n';
import { authoredSlugs } from '@/lib/translated-pages';

/**
 * Per-locale set of locale-agnostic docs paths that have an authored
 * translation. Computed once from the filesystem at module load (build time).
 * A path here is the `/docs/...` form with no locale prefix, e.g.
 * `/docs/install/quickstart` or `/docs` (the docs index).
 */
const TRANSLATED_PATHS: Record<string, Set<string>> = Object.fromEntries(
  ROUTED_NON_DEFAULT_LOCALES.map((lang) => {
    const paths = new Set<string>();
    for (const slug of authoredSlugs(lang)) {
      paths.add(slug.length === 0 ? '/docs' : `/docs/${slug.join('/')}`);
    }
    return [lang, paths];
  }),
);

/** Strip a leading routed-locale segment, yielding the locale-agnostic path. */
function localeAgnosticPath(pathname: string): string {
  const segments = pathname.split('/').filter((s) => s.length > 0);
  const first = segments[0];
  if (
    first &&
    first !== DEFAULT_LOCALE &&
    ROUTED_NON_DEFAULT_LOCALES.includes(first)
  ) {
    segments.shift();
  }
  const joined = `/${segments.join('/')}`;
  return joined === '/' ? '/' : joined.replace(/\/$/, '');
}

/**
 * Build the absolute URL for a locale's version of a locale-agnostic path.
 *
 * The source locale (English) is served at the site root with no prefix; every
 * other locale is served under its kebab-cased path segment.
 */
function localeUrl(locale: CohortLocale, agnosticPath: string): string {
  const normalized = agnosticPath === '/' ? '' : agnosticPath;
  if (locale.code === DEFAULT_LOCALE) {
    return `${SITE_URL}${normalized || '/'}`;
  }
  return `${SITE_URL}/${locale.path}${normalized}`;
}

/** Does `locale` have an authored translation of this locale-agnostic path?
 *
 * Resolves by the routed path segment (the `content/docs/<path>/` dir and the
 * `TRANSLATED_PATHS` key), not the BCP-47 `code`, so a locale whose code differs
 * from its path (e.g. `zh-CN` served under `zh-cn`) resolves correctly. */
function hasTranslation(locale: CohortLocale, agnosticPath: string): boolean {
  if (locale.code === DEFAULT_LOCALE) return true; // English is the source.
  // The landing page (`/`) has a localized counterpart for every routed
  // non-default locale (statically generated by app/[lang]/page.tsx), so its
  // hreflang cluster must include them — unlike docs pages, whose translations
  // are tracked per-authored-file in TRANSLATED_PATHS.
  if (agnosticPath === '/') return ROUTED_NON_DEFAULT_LOCALES.includes(locale.path);
  return TRANSLATED_PATHS[locale.path]?.has(agnosticPath) ?? false;
}

/**
 * Build the `alternates` object for a page at `pathname`.
 *
 * `pathname` may be locale-prefixed (e.g. `/es/docs/install`) or un-prefixed
 * (English). The returned `canonical` is the page's own absolute URL (never a
 * cross-locale URL); `languages` covers English, `x-default`, and any
 * non-default locale that has an authored translation of this page.
 *
 * The set is symmetric across locales because it is derived from the
 * locale-agnostic path, not from which locale's page is rendering.
 */
export function buildAlternates(pathname: string): {
  canonical: string;
  languages: Record<string, string>;
} {
  const agnostic = localeAgnosticPath(pathname);

  // Determine which locale this page is rendering, to build the self-canonical.
  const segments = pathname.split('/').filter((s) => s.length > 0);
  const first = segments[0];
  const renderingLocale =
    first && ROUTED_NON_DEFAULT_LOCALES.includes(first) && first !== DEFAULT_LOCALE
      ? first
      : DEFAULT_LOCALE;

  const languages: Record<string, string> = {};
  for (const locale of COHORT_LOCALES) {
    if (!hasTranslation(locale, agnostic)) continue;
    languages[locale.code] = localeUrl(locale, agnostic);
  }
  // x-default points to the source-locale URL — the fallback for visitors whose
  // Accept-Language matches no emitted cohort entry.
  languages['x-default'] = localeUrl(
    COHORT_LOCALES.find((l) => l.code === DEFAULT_LOCALE)!,
    agnostic,
  );

  // `renderingLocale` is the routed segment (path) for non-default locales and
  // DEFAULT_LOCALE for English, so match the default by code and the rest by
  // path — keeping locales whose code differs from their path (e.g. `zh-CN` /
  // `zh-cn`) self-canonical to their own URL, never cross-locale to English.
  const selfLocale =
    COHORT_LOCALES.find((l) =>
      l.code === DEFAULT_LOCALE
        ? renderingLocale === DEFAULT_LOCALE
        : l.path === renderingLocale,
    ) ?? COHORT_LOCALES.find((l) => l.code === DEFAULT_LOCALE)!;

  return {
    canonical: localeUrl(selfLocale, agnostic),
    languages,
  };
}
