#!/bin/sh
# SPDX-License-Identifier: MIT

# Purpose: Remove materialized harness configuration (self-contained — no
#          package to uninstall) and optionally remove the bundled source
#          tree at $APOTHEM_HOME.
# Contract: Idempotent. Confirms before removal unless --yes is supplied.
#           POSIX sh only (no bashisms): runs under dash/ash as well as bash.
#
# Usage:
#     bash scripts/installer/uninstall.sh [--yes] [--harness NAME] [--remove-source]
#
# Environment overrides:
#     APOTHEM_HOME     Bundled source location (default: $HOME/.apothem)
#     APOTHEM_SOURCE   Explicit local source tree to drive the CLI from
#     APOTHEM_HARNESS  Harness to uninstall (default: claude-code)

set -eu

APOTHEM_HOME="${APOTHEM_HOME:-$HOME/.apothem}"
HARNESS="${APOTHEM_HARNESS:-claude-code}"
ASSUME_YES=0
REMOVE_SOURCE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --yes|-y)         ASSUME_YES=1 ;;
        --harness)        HARNESS="$2"; shift ;;
        --remove-source)  REMOVE_SOURCE=1 ;;
        *) printf "Unknown option: %s\n" "$1" >&2; exit 1 ;;
    esac
    shift
done

# Colour only an interactive terminal. NO_COLOR (https://no-color.org/) or a
# redirected stream (a pipe, a file, a CI log) gets plain text; stdout and
# stderr are checked separately because die() writes to stderr.
COLOR_OUT=0
COLOR_ERR=0
if [ -z "${NO_COLOR:-}" ]; then
    if [ -t 1 ]; then COLOR_OUT=1; fi
    if [ -t 2 ]; then COLOR_ERR=1; fi
fi

# paint ENABLED SGR TEXT — print TEXT, wrapped in the SGR colour code when
# ENABLED is 1.
paint() {
    if [ "$1" = "1" ]; then
        printf '\033[%sm%s\033[0m' "$2" "$3"
    else
        printf '%s' "$3"
    fi
}

bold()  { printf '%s\n' "$(paint "$COLOR_OUT" 1 "$*")"; }
info()  { printf '  %s %s\n' "$(paint "$COLOR_OUT" 36 '·')" "$*"; }
ok()    { printf '  %s %s\n' "$(paint "$COLOR_OUT" 32 '✓')" "$*"; }
warn()  { printf '  %s %s\n' "$(paint "$COLOR_OUT" 33 '!')" "$*"; }
die()   { printf '  %s %s\n' "$(paint "$COLOR_ERR" 31 '✗')" "$*" >&2; exit 1; }

bold "Apothem uninstaller"
echo

is_apothem_source() {
    [ -d "$1/src/apothem" ] && { [ -f "$1/pyproject.toml" ] || [ -d "$1/.claude-plugin" ]; }
}

# Resolve a Python interpreter >= 3.10.
PY=""
for _cand in python3 python python3.14 python3.13 python3.12 python3.11 python3.10; do
    command -v "$_cand" >/dev/null 2>&1 || continue
    if "$_cand" -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3, 10) else 1)' >/dev/null 2>&1; then
        PY="$_cand"
        break
    fi
done
[ -n "$PY" ] || die "No Python >= 3.10 found in PATH — nothing to uninstall"

# Locate the bundled source so the CLI can drive the harness uninstall.
SOURCE=""
if [ -n "${APOTHEM_SOURCE:-}" ]; then
    SOURCE="$(cd "$APOTHEM_SOURCE" 2>/dev/null && pwd || true)"
    [ -n "$SOURCE" ] && is_apothem_source "$SOURCE" \
        || die "APOTHEM_SOURCE is not an apothem source tree: ${APOTHEM_SOURCE}"
elif is_apothem_source "$APOTHEM_HOME"; then
    SOURCE="$APOTHEM_HOME"
fi
[ -n "$SOURCE" ] || die "No apothem source found at $APOTHEM_HOME — nothing to uninstall"
SRC_PATH="${SOURCE}/src"

if [ "$ASSUME_YES" -eq 0 ]; then
    printf "  Remove %s harness configuration? [y/N] " "$HARNESS"
    read -r ANSWER
    case "$ANSWER" in
        [Yy]*) ;;
        *) warn "Aborted."; exit 0 ;;
    esac
fi

bold "Uninstalling harness: ${HARNESS}"
# Vendor-first PYTHONPATH mirrors the install/update invocations.
ENGINE_PYPATH="${SRC_PATH}/apothem/_vendor:${SRC_PATH}"
PYTHONPATH="${ENGINE_PYPATH}${PYTHONPATH:+:${PYTHONPATH}}" \
    "$PY" -m apothem uninstall --harness "$HARNESS" --yes
ok "Harness ${HARNESS} uninstalled"
echo

# Entry-point shim ---------------------------------------------------------------
#
# Remove the `apothem` PATH shim install.sh placed at
# ${APOTHEM_BIN_DIR:-$HOME/.local/bin}/apothem (same dir/filename derivation).
# Only the file carrying the install.sh-generated marker is removed, so an
# operator's own `apothem` on PATH is never touched. Idempotent: absent shim is
# a no-op. Never removes the directory — only the specific shim file.
SHIM_BIN_DIR="${APOTHEM_BIN_DIR:-$HOME/.local/bin}"
SHIM="${SHIM_BIN_DIR}/apothem"
SHIM_MARKER='# Apothem entry-point shim (generated by install.sh).'
if [ -f "$SHIM" ] && grep -qF "$SHIM_MARKER" "$SHIM" 2>/dev/null; then
    if rm -f "$SHIM" 2>/dev/null; then
        ok "Removed apothem command: $SHIM"
    else
        warn "Could not remove the apothem shim at $SHIM — remove it manually."
    fi
fi
echo

if [ "$REMOVE_SOURCE" -eq 1 ]; then
    # Only the managed clone at APOTHEM_HOME is removable; an explicit
    # APOTHEM_SOURCE (operator's own checkout) is never deleted.
    if [ "$SOURCE" = "$APOTHEM_HOME" ] && [ -d "$APOTHEM_HOME/.git" ]; then
        if [ "$ASSUME_YES" -eq 0 ]; then
            printf "  Remove the bundled source at %s? [y/N] " "$APOTHEM_HOME"
            read -r ANSWER
            case "$ANSWER" in
                [Yy]*) ;;
                *) warn "Kept the bundled source."; SOURCE=""; ;;
            esac
        fi
        if [ -n "$SOURCE" ]; then
            bold "Removing bundled source"
            rm -rf "$APOTHEM_HOME"
            ok "Removed $APOTHEM_HOME"
        fi
    else
        warn "Source at $SOURCE is operator-owned (not the managed clone) — not removed."
    fi
fi
echo

bold "Uninstall complete."
cat <<EOF

Next steps:
  1. Remove another harness:        bash scripts/installer/uninstall.sh --harness <name>
  2. Remove the bundled source too: bash scripts/installer/uninstall.sh --remove-source --yes
  3. Re-install a harness later:    bash scripts/installer/install.sh

EOF
