# SPDX-License-Identifier: MIT

"""Behavior-diff oracle for the cli/__init__.py decomposition (DX-2 support).

Deterministic, byte-reproducible capture of the whole CLI surface's observable
behavior across a fixed invocation matrix, normalized so the corpus is identical
across runs and machines. The committed golden corpus at
``tests/fixtures/behavior-diff/cli/`` was generated by the matching capture and
``test_cli_behavior_diff.py`` re-runs this oracle and asserts byte-equality, so
any future change that alters a command's stdout / JSON envelope / exit code is
caught. The underscore prefix keeps pytest from collecting this helper as tests.

Isolation: ``HOME`` / ``USERPROFILE`` / ``XDG_CONFIG_HOME`` are redirected to a
per-invocation scratch home, ``Path.home`` is patched, and
``install_driver.BACKUP_ROOT`` / ``install_ledger.STATE_ROOT`` point into the
scratch tree, so ``status`` / ``verify`` / ``diff`` / ``doctor`` /
``harnesses list`` see an empty, deterministic world independent of the
operator's real ``~/.claude`` / ``~/.apothem`` / ``$HOME``. The Rich render
width is pinned via ``COLUMNS`` so table columns never truncate a path on the
random ``mkdtemp`` suffix.
"""

from __future__ import annotations

import contextlib
import json
import os
import platform
import re
import shutil
import sys
import tempfile
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any

from click.testing import CliRunner

import apothem
from apothem.cli import main
from apothem.harnesses._shared import install_driver
from apothem.lib import install_ledger

from ._oracle_norm import (
    _ISO_TS_RE,
    _PYBIN_RE,
    _TS_RE,
    _ULID_RE,
    TOK_INSTALL_ID,
    TOK_PYBIN,
    TOK_ROOT,
    TOK_SRC,
    TOK_TIMESTAMP,
    collapse_token_paths,
    normalize_obj,
)

TOK_VERSION = "<VERSION>"
TOK_HOME = "<HOME>"

_VERSION = apothem.__version__
_VERSION_RE = re.compile(re.escape(_VERSION))

# `doctor` reports the live interpreter version and OS; both vary by machine, so
# neutralize the exact values this capture's interpreter would emit (they appear
# verbatim in the text, JSON, and escaped-JSON forms of the doctor output).
_TOK_PYVER = "<PYVER>"
_TOK_PLATFORM = "<PLATFORM>"
_PYVER = sys.version.split()[0]
_PLATFORM = f"{platform.system()} {platform.release()}"

_SAMPLE_HARNESS = "claude-code"
_COMPLETION_SHELLS = ("bash", "zsh", "fish", "powershell")
_HELP_COMMANDS = (
    "completion",
    "install",
    "quickstart",
    "uninstall",
    "rollback",
    "update",
    "verify",
    "status",
    "diff",
    "doctor",
    "profile",
    "harnesses",
)


def _path_variants(value: Path) -> set[str]:
    bases = {str(value), str(value.resolve())}
    variants: set[str] = set()
    for base in bases:
        variants.add(base)
        variants.add(base.replace("\\", "/"))
        variants.add(base.replace("\\", "\\\\"))
    variants.add(value.resolve().as_posix())
    return {v for v in variants if v}


def _normalize_text(text: str, *, home: Path) -> str:
    # Three machine-specific roots are tokenized: the scratch home, the temp
    # root, and the apothem package source root (embedded in plan `source`
    # fields that `diff` echoes). They can nest — the scratch home always sits
    # under the temp root, and a checkout cloned under $TMPDIR puts the source
    # root there too — so all spellings are replaced longest-first in one pass.
    # Replacing the temp root before a root nested inside it would rewrite
    # `<src>/...` to `<ROOT>/clone/src/...` and drift the golden for a reason
    # unrelated to the change under test.
    replacements = [
        (variant, token)
        for token, root in (
            (TOK_HOME, home),
            (TOK_ROOT, Path(tempfile.gettempdir())),
            (TOK_SRC, install_driver.APOTHEM_SRC),
        )
        for variant in _path_variants(root)
    ]
    for variant, token in sorted(
        replacements, key=lambda pair: len(pair[0]), reverse=True
    ):
        text = text.replace(variant, token)
    text = _ISO_TS_RE.sub(TOK_TIMESTAMP, text)
    text = _TS_RE.sub(TOK_TIMESTAMP, text)
    text = _ULID_RE.sub(TOK_INSTALL_ID, text)
    text = _PYBIN_RE.sub(f'"{TOK_PYBIN}"', text)
    text = _VERSION_RE.sub(TOK_VERSION, text)
    text = text.replace(_PLATFORM, _TOK_PLATFORM)
    text = text.replace(_PYVER, _TOK_PYVER)
    return collapse_token_paths(text, "HOME|ROOT|APOTHEM_SRC")


def _normalize_obj(obj: Any, *, home: Path) -> Any:  # noqa: ANN401  # Any: recurses over arbitrary JSON-like envelopes
    return normalize_obj(obj, lambda s: _normalize_text(s, home=home))


@contextlib.contextmanager
def _isolated_home() -> Iterator[Path]:
    scratch = Path(tempfile.mkdtemp(prefix="dx2-cli-"))
    home = scratch / "home"
    home.mkdir(parents=True, exist_ok=True)
    saved_env = {
        key: os.environ.get(key)
        for key in (
            "HOME",
            "USERPROFILE",
            "XDG_CONFIG_HOME",
            "APOTHEM_HOME",
            "COLUMNS",
            "LINES",
        )
    }
    saved_home_fn = Path.home
    saved_backup = install_driver.BACKUP_ROOT
    saved_state = install_ledger.STATE_ROOT
    try:
        os.environ["HOME"] = str(home)
        os.environ["USERPROFILE"] = str(home)
        os.environ["XDG_CONFIG_HOME"] = str(home / ".config")
        os.environ["APOTHEM_HOME"] = str(scratch / "apothem-home")
        # Pin a wide console so Rich never wraps a long temp-home path: wrap
        # points depend on the real (pre-tokenization) path length, which
        # differs per machine, so wrapping would bake machine-specific newlines
        # into the golden. 1000 columns clears the longest realistic temp path.
        os.environ["COLUMNS"] = "1000"
        os.environ["LINES"] = "50"
        Path.home = classmethod(lambda cls: home)  # type: ignore[assignment]
        install_driver.BACKUP_ROOT = scratch / "backups"
        install_ledger.STATE_ROOT = scratch / "ledger-state"
        yield home
    finally:
        Path.home = saved_home_fn  # type: ignore[assignment]
        install_driver.BACKUP_ROOT = saved_backup
        install_ledger.STATE_ROOT = saved_state
        for key, value in saved_env.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value
        shutil.rmtree(scratch, ignore_errors=True)


def capture_one(
    out_root: Path, slug: str, argv: Sequence[str], *, seed_profile: bool
) -> None:
    """Capture one invocation's normalized record to ``out_root/<slug>.json``."""
    runner = CliRunner()
    with _isolated_home() as home:
        if seed_profile:
            init = runner.invoke(main, ["profile", "init"], catch_exceptions=False)
            if init.exit_code != 0:  # pragma: no cover - defensive
                raise RuntimeError(f"profile init seed failed: {init.output}")
        result = runner.invoke(main, list(argv), catch_exceptions=False)
        stdout = _normalize_text(result.output, home=home)
        record: dict[str, Any] = {
            "argv": list(argv),
            "exit_code": result.exit_code,
            "stdout": stdout,
        }
        if "--json" in argv or "json" in argv:
            with contextlib.suppress(json.JSONDecodeError):
                record["json"] = _normalize_obj(json.loads(result.output), home=home)
    dest = out_root / f"{slug}.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        json.dumps(record, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def matrix() -> list[tuple[str, list[str], bool]]:
    """Return the fixed (slug, argv, seed_profile) invocation matrix."""
    rows: list[tuple[str, list[str], bool]] = []
    rows.append(("root-help", ["--help"], False))
    rows.append(("root-version", ["--version"], False))
    for cmd in _HELP_COMMANDS:
        rows.append((f"help-{cmd}", [cmd, "--help"], False))
    for sub in ("show", "init", "set", "edit"):
        rows.append((f"help-profile-{sub}", ["profile", sub, "--help"], False))
    for sub in ("list", "show"):
        rows.append((f"help-harnesses-{sub}", ["harnesses", sub, "--help"], False))
    for shell in _COMPLETION_SHELLS:
        rows.append((f"completion-{shell}", ["completion", shell], False))
    rows.append(("harnesses-list", ["harnesses", "list"], False))
    rows.append(("harnesses-list-json", ["harnesses", "list", "--json"], False))
    rows.append(("harnesses-show", ["harnesses", "show", _SAMPLE_HARNESS], False))
    rows.append(
        ("harnesses-show-json", ["harnesses", "show", _SAMPLE_HARNESS, "--json"], False)
    )
    rows.append(("status", ["status"], True))
    rows.append(("status-json", ["status", "--json"], True))
    rows.append(("verify-all", ["verify", "--harness", "all"], True))
    rows.append(("verify-all-json", ["verify", "--harness", "all", "--json"], True))
    rows.append(("diff-claude-code", ["diff", "--harness", _SAMPLE_HARNESS], True))
    rows.append(
        (
            "diff-claude-code-json",
            ["diff", "--harness", _SAMPLE_HARNESS, "--json"],
            True,
        )
    )
    rows.append(("doctor", ["doctor"], False))
    rows.append(("doctor-json", ["doctor", "--json"], False))
    rows.append(("profile-init", ["profile", "init"], False))
    rows.append(("profile-show", ["profile", "show"], True))
    rows.append(("profile-show-json", ["profile", "show", "--json"], True))
    rows.append(("err-unknown-harness", ["verify", "--harness", "bogus"], False))
    rows.append(
        ("err-unknown-harness-json", ["verify", "--harness", "bogus", "--json"], False)
    )
    rows.append(("err-diff-all-rejected", ["diff", "--harness", "all"], False))
    rows.append(
        ("err-diff-all-rejected-json", ["diff", "--harness", "all", "--json"], False)
    )
    # A first install without --profile creates the default profile, so the
    # missing-profile error is pinned with an explicit --profile that does not
    # exist (``~`` expands to the scratch home), and the first-run success has
    # its own plain row.
    missing_profile = ["--profile", "~/.config/apothem/missing.yaml"]
    rows.append(
        (
            "err-install-missing-profile",
            ["install", "--harness", _SAMPLE_HARNESS, *missing_profile],
            False,
        )
    )
    rows.append(
        (
            "err-install-missing-profile-json",
            ["install", "--harness", _SAMPLE_HARNESS, *missing_profile, "--json"],
            False,
        )
    )
    rows.append(("install-first-run", ["install", "--harness", _SAMPLE_HARNESS], False))
    return rows


def capture(out_root: Path) -> int:
    """Capture every matrix invocation into *out_root*. Returns the count."""
    if out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    rows = matrix()
    for slug, argv, seed in rows:
        capture_one(out_root, slug, argv, seed_profile=seed)
    return len(rows)
