# SPDX-License-Identifier: MIT

"""Behavior-diff oracle for the install_driver decomposition (DX-1 support).

Canonical, deterministic capture of install_driver's observable behavior across
the adapter matrix, normalized so the corpus is byte-reproducible across runs
and machines. The committed golden corpus at
``tests/fixtures/behavior-diff/install_driver/`` was generated by this oracle;
``test_install_driver_behavior_diff.py`` re-runs it and asserts byte-equality,
so any future change that alters rendered output / dispatch / ledger behavior is
caught. The underscore prefix keeps pytest from collecting this helper as tests.

HOME isolation: ``BACKUP_ROOT``, the ledger ``STATE_ROOT``, and the data-home
base are all redirected into per-adapter scratch, so a capture never touches the
operator's real ``~/.claude`` / ``~/.codex`` / ``~/.apothem`` / ``$HOME``.
"""

from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path
from typing import Any

from apothem.harnesses._shared import install_driver
from apothem.lib import install_ledger
from apothem.lib.harness_registry import HARNESS_REGISTRY

from ._oracle_norm import (
    _ISO_TS_RE,
    _TS_RE,
    _ULID_RE,
    TOK_INSTALL_ID,
    TOK_ROOT,
    TOK_SRC,
    TOK_TIMESTAMP,
    collapse_token_paths,
    normalize_obj,
    tokenize_python_bin,
)

# A single fixed sample profile reused for every adapter; every projected
# section carries a stable greppable sentinel.
SAMPLE_PROFILE: dict[str, Any] = {
    "identity": {
        "name": "Golden-Corpus-Operator",
        "role": "release engineer",
        "email": "golden@corpus.invalid",
        "website": "https://golden.corpus.invalid",
        "github": "golden-corpus-operator",
    },
    "preferences": {"language": "python", "style": "concise"},
    "rules": ["golden-corpus-validate-input-before-write"],
    "seriousness": "PUBLIC_LAUNCH",
    "enforcement": {"sprints": True},
    "mcp_servers": {
        "golden-corpus-srv": {"transport": "stdio", "command": "golden-corpus-cmd"}
    },
}

# The backup-directory stamp is tokenized to its own ``<BACKUP_TS>`` marker
# (distinct from the shared ``<TIMESTAMP>`` used for ISO-8601 stamps), so this
# oracle keeps its own token; the rest of the normalization constants are the
# byte-identical primitives shared with the CLI oracle.
TOK_BACKUP_TS = "<BACKUP_TS>"

ALL_ADAPTERS: list[str] = [entry.package_key for entry in HARNESS_REGISTRY]


def _scope_kwarg(name: str, root: Path) -> dict[str, Path]:
    entry = next(e for e in HARNESS_REGISTRY if e.package_key == name)
    if entry.scope == "project":
        return {"project_root": root}
    return {"harness_root": root}


def _path_variants(path: Path) -> set[str]:
    """Every spelling of *path* that can appear in captured text."""
    return {
        str(path),
        str(path.resolve()),
        path.resolve().as_posix(),
        str(path).replace("\\", "/"),
    }


def _normalize_text(text: str, *, root: Path, outer: Path | None = None) -> str:
    # The scratch install root AND the apothem package source root (embedded in
    # plan `source` fields) are both machine-specific absolute paths; neutralize
    # both so a Windows capture and a Linux capture are byte-identical. *outer*
    # is the private scratch directory holding the install root: a layout whose
    # manifest targets reach above the harness root (`${HARNESS_ROOT}/../`)
    # names paths under it, which read as `<ROOT>/..`. Only a directory created
    # for the capture is passed, never a shared temp root.
    replacements = [(TOK_ROOT, _path_variants(root))]
    if outer is not None:
        replacements.append((f"{TOK_ROOT}/..", _path_variants(outer)))
    replacements.append((TOK_SRC, _path_variants(install_driver.APOTHEM_SRC)))
    for token, variants in replacements:
        for variant in sorted(variants, key=len, reverse=True):
            if variant:
                text = text.replace(variant, token)
    text = _ISO_TS_RE.sub(TOK_TIMESTAMP, text)
    text = _TS_RE.sub(TOK_BACKUP_TS, text)
    text = _ULID_RE.sub(TOK_INSTALL_ID, text)
    return collapse_token_paths(text, "ROOT|APOTHEM_SRC")


def _normalize_obj(obj: Any, *, root: Path, outer: Path | None = None) -> Any:  # noqa: ANN401  # Any: recurses over arbitrary JSON-like structures (build_plan / to_dict output)
    return normalize_obj(obj, lambda s: _normalize_text(s, root=root, outer=outer))


def _ledger_target_key(target: dict[str, Any]) -> tuple[str, str]:
    """Order ledger targets by tokenized POSIX path, then by full content.

    Python compares ``str`` by code point, independent of platform and locale.
    The path is unique within a record (the ledger drops duplicate paths); the
    canonical JSON tie-breaker keeps the order total regardless.
    """
    return (str(target["path"]), json.dumps(target, sort_keys=True))


def _sort_ledger_targets(record: dict[str, Any]) -> dict[str, Any]:
    """Return *record* with its ``targets`` in one platform-independent order.

    The ledger lists targets in install order, and the installer walks each
    source directory with ``sorted()`` over ``Path`` objects. A Windows path
    compares case-insensitively and a POSIX path by code point, so
    ``schemas/NOTICE.md`` installs before ``__init__.py`` on POSIX and after
    ``advisory-finding.schema.json`` on Windows. Sorting the normalized
    targets gives every platform the same bytes. The comparison side already
    ignores array order (``canon_ledger`` deep-sorts), so no assertion changes.
    """
    targets = record.get("targets")
    if isinstance(targets, list):
        record["targets"] = sorted(targets, key=_ledger_target_key)
    return record


def _dump_json(obj: Any, dest: Path) -> None:  # noqa: ANN401  # Any: serializes arbitrary JSON-like structures
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _snapshot_rendered_tree(
    root: Path, dest_dir: Path, *, outer: Path | None = None
) -> None:
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        rel = path.relative_to(root)
        if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
            continue
        # The memory store writes `<root>/.apothem/memory/records.json`
        # on every install, but `memory/` is gitignored repo-wide, so the golden
        # cannot be committed and is absent on a fresh CI checkout. Skip it so the
        # captured file-set matches the committed (memory-less) corpus on every
        # platform.
        if "memory" in rel.parts:
            continue
        dest = dest_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        raw = path.read_bytes()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            dest.write_bytes(raw)
            continue
        normalized = tokenize_python_bin(_normalize_text(text, root=root, outer=outer))
        dest.write_text(normalized, encoding="utf-8", newline="\n")


def _capture_plan(name: str, out_root: Path) -> None:
    root = Path(tempfile.mkdtemp(prefix=f"dx1-plan-{name}-"))
    try:
        plan = install_driver.build_plan(name, **_scope_kwarg(name, root))
        _dump_json(_normalize_obj(plan, root=root), out_root / "plan" / f"{name}.json")
    finally:
        shutil.rmtree(root, ignore_errors=True)


def _capture_dryrun(name: str, out_root: Path) -> None:
    # The root sits in a private scratch directory, as in the real-install
    # capture, so a path the preview names above the harness root reads as
    # `<ROOT>/..` instead of carrying the machine's temp directory.
    scratch = Path(tempfile.mkdtemp(prefix=f"dx1-dry-{name}-"))
    root = scratch / "install"
    root.mkdir()
    try:
        run = install_driver.run_install(
            name, dry_run=True, profile=SAMPLE_PROFILE, **_scope_kwarg(name, root)
        )
        results = [result.to_dict() for result in run.results]
        _dump_json(
            _normalize_obj(results, root=root, outer=scratch),
            out_root / "dryrun" / f"{name}.json",
        )
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _capture_real_install(name: str, out_root: Path) -> None:
    scratch = Path(tempfile.mkdtemp(prefix=f"dx1-real-{name}-"))
    install_root = scratch / "install"
    backup_root = scratch / "backups"
    ledger_state = scratch / "ledger-state"
    install_root.mkdir(parents=True, exist_ok=True)
    backup_root.mkdir(parents=True, exist_ok=True)
    saved_backup = install_driver.BACKUP_ROOT
    saved_state = install_ledger.STATE_ROOT
    try:
        install_driver.BACKUP_ROOT = backup_root
        install_ledger.STATE_ROOT = ledger_state
        run = install_driver.run_install(
            name, profile=SAMPLE_PROFILE, **_scope_kwarg(name, install_root)
        )
        install_driver.finalize_install(run, root=install_root)

        rendered_dir = out_root / "rendered" / name
        if rendered_dir.exists():
            shutil.rmtree(rendered_dir)
        _snapshot_rendered_tree(install_root, rendered_dir, outer=scratch)

        ledger_lines: list[str] = []
        if ledger_state.exists():
            for ledger_file in sorted(ledger_state.rglob("*")):
                if ledger_file.is_file():
                    for line in ledger_file.read_text(encoding="utf-8").splitlines():
                        if not line.strip():
                            continue
                        norm = _normalize_obj(json.loads(line), root=install_root)
                        norm = _sort_ledger_targets(
                            _normalize_obj(norm, root=backup_root)
                        )
                        ledger_lines.append(
                            json.dumps(norm, sort_keys=True, ensure_ascii=False)
                        )
        ledger_dest = out_root / "ledger" / f"{name}.jsonl"
        ledger_dest.parent.mkdir(parents=True, exist_ok=True)
        ledger_dest.write_text(
            ("\n".join(ledger_lines) + "\n") if ledger_lines else "",
            encoding="utf-8",
            newline="\n",
        )

        envelope = {
            "harness": run.harness,
            "dry_run": run.dry_run,
            "changed": run.changed,
            "files_written": sorted(
                _normalize_text(p, root=install_root) for p in run.files_written
            ),
            "warnings": len(run.warnings),
            "counts": run.counts,
        }
        _dump_json(
            _normalize_obj(envelope, root=install_root),
            out_root / "envelope" / f"{name}.json",
        )
    finally:
        install_driver.BACKUP_ROOT = saved_backup
        install_ledger.STATE_ROOT = saved_state
        shutil.rmtree(scratch, ignore_errors=True)


def capture(
    out_root: Path, *, fast_adapters: list[str], real_adapters: list[str]
) -> None:
    """Capture plan+dryrun for *fast_adapters* and full real install for *real_adapters*."""
    for name in fast_adapters:
        _capture_plan(name, out_root)
        _capture_dryrun(name, out_root)
    for name in real_adapters:
        _capture_real_install(name, out_root)


def capture_full(out_root: Path) -> None:
    """Regenerate the complete committed corpus (all corpora, all adapters)."""
    if out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    for name in ALL_ADAPTERS:
        _capture_plan(name, out_root)
        _capture_dryrun(name, out_root)
        _capture_real_install(name, out_root)
