# SPDX-License-Identifier: MIT

# Run this script after a CLI surface change to re-emit the completion scripts;
# byte-identical regeneration is the verification check.

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$Root = (Resolve-Path "$PSScriptRoot\..\..").Path
$Out = Join-Path $Root "src\apothem\cli\completions"
New-Item -ItemType Directory -Force -Path $Out | Out-Null

# The committed goldens under src/apothem/cli/completions/ are ASCII, BOM-free,
# and LF-terminated. PowerShell's `>` redirection emits UTF-16LE + BOM + CRLF,
# which would diverge from the goldens byte-for-byte; capture stdout instead and
# write it back with an explicit BOM-free UTF-8 encoding and normalized LF EOLs.
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
foreach ($shell in @("bash", "zsh", "fish")) {
    $env:_APOTHEM_COMPLETE = "${shell}_source"
    $target = Join-Path $Out "apothem.$shell"
    $output = $null
    try {
        $output = & apothem
    } catch {
        # Command name did not resolve (apothem not on PATH).
        $LASTEXITCODE = 1
    }
    if ($LASTEXITCODE -ne 0) {
        # Falls back on both an unresolved command name and a non-zero exit, so a
        # broken CLI triggers the python entry point rather than truncating the golden.
        Write-Host "apothem unavailable on PATH; falling back to: python -c"
        $output = & python -c "from apothem.cli import main; main()"
    }
    [System.IO.File]::WriteAllText($target, (($output -join "`n") + "`n"), $Utf8NoBom)
    Remove-Item Env:_APOTHEM_COMPLETE
    Write-Host "  + apothem.$shell"
}

# PowerShell is generated by the completion class the CLI registers; the
# `completion powershell` command pins the `apothem` program name so the
# emitted script never carries the invoking interpreter's name.
$psTarget = Join-Path $Out "apothem.ps1"
$psOutput = $null
try {
    $psOutput = & apothem completion powershell
} catch {
    $LASTEXITCODE = 1
}
if ($LASTEXITCODE -ne 0) {
    Write-Host "apothem unavailable on PATH; falling back to: python -m apothem"
    $psOutput = & python -m apothem completion powershell
}
$psHeader = "# SPDX-License-Identifier: MIT`n`n"
[System.IO.File]::WriteAllText($psTarget, ($psHeader + (($psOutput -join "`n") + "`n")), $Utf8NoBom)
Write-Host "  + apothem.ps1"

Write-Host "Regeneration complete -> $Out"
