#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

# Run this script after a CLI surface change to re-emit the completion scripts;
# byte-identical regeneration is the verification check.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/src/apothem/cli/completions"
mkdir -p "$OUT"

# Every script is generated by `apothem completion <shell>`, which pins the
# `apothem` program name so the emitted script never carries the invoking
# interpreter's name. (Click's `<shell>_source` env-var path derives the name
# from the invocation, so under `python -m apothem` it would emit
# `_python_mapothem_completion` functions.) Each golden is the SPDX header
# followed by the command's output.
#
# Generate into a temp file and promote atomically only on success: shell
# redirection opens its target with O_TRUNC before the command runs, so writing
# straight to the golden destroyed it the instant a generator failed. The
# quieter case is worse — a generator that exits 0 emitting nothing left a
# header-only file that the byte-identical verification check then treats as
# canonical, while the script still printed success.
for shell in bash zsh fish powershell; do
  case "$shell" in
    powershell) golden="apothem.ps1" ;;
    *) golden="apothem.$shell" ;;
  esac
  _body="$(mktemp "$OUT/.$golden.body.XXXXXX")"
  _out="$(mktemp "$OUT/.$golden.XXXXXX")"
  if ! apothem completion "$shell" > "$_body" 2>/dev/null; then
    echo "apothem not on PATH; falling back to: python -m apothem" >&2
    if ! python -m apothem completion "$shell" > "$_body"; then
      rm -f "$_body" "$_out"
      echo "error: failed to regenerate $golden (apothem off PATH and the python fallback failed; run under PYTHONPATH=src)" >&2
      exit 1
    fi
  fi
  if [ ! -s "$_body" ]; then
    rm -f "$_body" "$_out"
    echo "error: $golden generated empty; refusing to overwrite the golden" >&2
    exit 1
  fi
  {
    printf '# SPDX-License-Identifier: MIT\n\n'
    cat "$_body"
  } > "$_out"
  rm -f "$_body"
  mv "$_out" "$OUT/$golden"
  printf '  ✓ %s\n' "$golden"
done

echo "Regeneration complete → $OUT"
