#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

# Run this script after a CLI surface change to re-emit the completion scripts;
# byte-identical regeneration is the verification check.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/src/apothem/cli/completions"
mkdir -p "$OUT"

for shell in bash zsh fish; do
  # Generate into a temp file and promote atomically only on success, so a
  # failed generation never leaves a truncated/empty golden that the byte-
  # identical verification check would then treat as canonical.
  _tmp="$(mktemp "$OUT/.apothem.$shell.XXXXXX")"
  if _APOTHEM_COMPLETE="${shell}_source" apothem > "$_tmp" 2>/dev/null; then
    :
  else
    echo "apothem not on PATH; falling back to: python -c 'from apothem.cli import main; main()'" >&2
    if ! _APOTHEM_COMPLETE="${shell}_source" python -c "from apothem.cli import main; main()" > "$_tmp" 2>/dev/null; then
      rm -f "$_tmp"
      echo "error: failed to regenerate apothem.$shell (apothem off PATH and the python fallback failed; run under PYTHONPATH=src)" >&2
      exit 1
    fi
  fi
  if [ ! -s "$_tmp" ]; then
    rm -f "$_tmp"
    echo "error: apothem.$shell generated empty; refusing to overwrite the golden" >&2
    exit 1
  fi
  mv "$_tmp" "$OUT/apothem.$shell"
  printf '  ✓ %s\n' "apothem.$shell"
done

# PowerShell is generated by the completion class the CLI registers; the
# `completion powershell` command pins the `apothem` program name so the
# emitted script never carries the invoking interpreter's name.
#
# Same temp-file discipline as the loop above, and for the same reason: shell
# redirection opens its target with O_TRUNC before the command runs, so writing
# the group straight to the golden destroyed it the instant a generator failed.
# The quieter case is worse — a generator that exits 0 emitting nothing left a
# header-only file that the byte-identical verification check then treats as
# canonical, while the script still printed success.
_body="$(mktemp "$OUT/.apothem.ps1.body.XXXXXX")"
_out="$(mktemp "$OUT/.apothem.ps1.XXXXXX")"
if ! { apothem completion powershell 2>/dev/null \
    || python -m apothem completion powershell; } > "$_body"; then
  rm -f "$_body" "$_out"
  echo "error: failed to regenerate apothem.ps1 (apothem off PATH and the python fallback failed; run under PYTHONPATH=src)" >&2
  exit 1
fi
if [ ! -s "$_body" ]; then
  rm -f "$_body" "$_out"
  echo "error: apothem.ps1 generated empty; refusing to overwrite the golden" >&2
  exit 1
fi
{
  printf '# SPDX-License-Identifier: MIT\n\n'
  cat "$_body"
} > "$_out"
rm -f "$_body"
mv "$_out" "$OUT/apothem.ps1"
printf '  ✓ %s\n' "apothem.ps1"

echo "Regeneration complete → $OUT"
