# SPDX-License-Identifier: MIT

"""Guard the PWA-manifest icon set against the canonical asset generator.

The asset corpus is regenerated by a single canonical generator,
``scripts/dev/rebuild-assets-resvg.py``. The PWA web-app manifest at
``site/public/manifest.json`` references a set of icons (favicons, the
``purpose: any`` logo sizes, and the ``purpose: maskable`` tiles); every one
MUST be produced by the generator, committed under ``assets/``, and mirrored
into ``site/public/`` where the manifest serves it.

This test is the anti-divergence guard: it fails the moment the manifest
references an icon the generator does not produce / ship, or an icon whose
committed output is missing — the exact regression class that let a now-retired
second rebuild path silently drop the maskable and ``logo-192`` icons the
manifest needs.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]
_ASSETS = _REPO_ROOT / "assets"
_SITE_PUBLIC = _REPO_ROOT / "site" / "public"
_MANIFEST = _SITE_PUBLIC / "manifest.json"
_GENERATOR = _REPO_ROOT / "scripts" / "dev" / "rebuild-assets-resvg.py"


def _manifest_icon_basenames() -> list[str]:
    """Return the basename of every icon ``src`` declared in the manifest."""

    data = json.loads(_MANIFEST.read_text(encoding="utf-8"))
    icons = data.get("icons", [])
    # Web paths are forward-slash regardless of host OS; split portably.
    return [str(icon["src"]).rsplit("/", 1)[-1] for icon in icons]


def test_manifest_present() -> None:
    assert _MANIFEST.is_file(), f"PWA manifest missing at {_MANIFEST}"
    assert _GENERATOR.is_file(), f"Canonical generator missing at {_GENERATOR}"


def test_manifest_declares_icons() -> None:
    icons = _manifest_icon_basenames()
    # The manifest is meaningless without icons; an empty set would make the
    # coverage assertions below vacuously pass.
    assert icons, "manifest.json declares no icons"


@pytest.mark.parametrize("icon", _manifest_icon_basenames())
def test_manifest_icon_committed_in_assets(icon: str) -> None:
    assert (_ASSETS / icon).is_file(), (
        f"manifest references {icon!r} but assets/{icon} is not committed — "
        "regenerate with scripts/dev/rebuild-assets-resvg.py"
    )


@pytest.mark.parametrize("icon", _manifest_icon_basenames())
def test_manifest_icon_mirrored_to_site_public(icon: str) -> None:
    assert (_SITE_PUBLIC / icon).is_file(), (
        f"manifest references {icon!r} but site/public/{icon} is not mirrored — "
        "rerun scripts/dev/rebuild-assets-resvg.py to mirror it"
    )


@pytest.mark.parametrize("icon", _manifest_icon_basenames())
def test_manifest_icon_produced_by_generator(icon: str) -> None:
    # The generator's site/public mirror list names every shipped asset by
    # literal basename; absence here means the generator neither produces nor
    # ships the icon, so the manifest would reference an asset nothing emits.
    generator_text = _GENERATOR.read_text(encoding="utf-8")
    assert icon in generator_text, (
        f"manifest references {icon!r} but the canonical generator "
        "scripts/dev/rebuild-assets-resvg.py never names it — add it to the "
        "generation and site mirror steps so the corpus cannot silently diverge"
    )
